# @package _global_

model:
  _target_: cs336_basics.model.Transformer
  d_model: 512
  num_heads: 16
  d_ff: 1344  # 2048 for SiLU
  rope_theta: 10000
  vocab_size: 10000  # TinyStories
  # vocab_size: 32000  # OWT
  context_length: 256
  num_layers: 4
  device: ??
